# Generated by Django 3.0.5 on 2020-11-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201030_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.DeleteModel(
            name='Titles',
        ),
    ]
